#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}
module_id = os.environ['MODULE_ID']

# Read the packages
rdb = agent.redis_connect(privileged=False)
config["packages"] = rdb.hgetall(f"module/{module_id}/composer")

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
