#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Ensure file exists
if not os.path.exists('packages.json'):
    with open('packages.json', 'w') as f:
        json.dump({"packages": {}, "repositories": []}, f, indent=2)

with open('packages.json') as f:
    packageData = json.load(f)

# Dump the configuration to stdout
json.dump(packageData, fp=sys.stdout)
