#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent

agent.set_weight(os.path.basename(__file__), 0) # Validation step, no task progress at all

# retrieve json data
data = json.load(sys.stdin)

# Setup default values
host = data.get("host")
# do not test if it is the same host
oldHost = os.environ.get('TRAEFIK_HOST','')

if host != oldHost and agent.http_route_in_use(domain=host):
    agent.set_status('validation-failed')
    json.dump([{'field':'host','parameter':'host','value':host,'error':'domain_already_used_in_traefik'}],fp=sys.stdout)
    sys.exit(2)

additional_hosts = data.get("additionalHostnames")
given_hosts = os.environ.get('ADDITIONAL_HOSTS','').split(',')
additional_hosts_list = []
for additional_host in additional_hosts.splitlines():
    if not agent.http_route_in_use(domain=additional_host) or additional_host in given_hosts:
        additional_hosts_list.append(additional_host)

agent.set_env('ADDITIONAL_HOSTS', ','.join(additional_hosts_list))