#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
set -e

# Redirect any output to the journal (stderr)
exec 1>&2

# If the control reaches this step, the service can be enabled and started

touch smarthost.env

systemctl --user enable typo3.service
systemctl --user restart typo3.service

# podman exec --user www-data typo3-app cp ./vendor/typo3/cms-install/Resources/Private/FolderStructureTemplateFiles/root-htaccess ./public/.htaccess
