#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os
import subprocess
import time

data = json.load(sys.stdin)

# Save packages to redis
if os.getenv('INITIALIZED', default = 'False') == 'False':
    schema = "http"

    if os.getenv('TRAEFIK_LETS_ENCRYPT', default = False):
        schema = "https"

    domain = os.getenv("TRAEFIK_HOST")
    fqdn = f"{schema}://{domain}"

    # Wait for running podman container
    time.sleep(5)
    subprocess.run(["podman", "wait", "--condition=running", "typo3-app"])

    # Fix directory problems
    subprocess.run(["podman", "exec", "typo3-app", "chown", "-R", "www-data", "config/"])

    proc = subprocess.run(
        [
            "podman",
            "exec",
            "--user=www-data",
            "typo3-app",
            "./vendor/bin/typo3",
            "setup",
            "--server-type",
            "apache",
            "--driver",
            "postgres",
            "--host",
            "127.0.0.1",
            "--port",
            "5432",
            "--dbname",
            "typo3",
            "--username",
            "postgres",
            "--password",
            "Nethesis,1234",
            "--admin-username",
            data.get('adminUsername', "admin"),
            "--admin-user-password",
            data.get('adminPassword', "Nethesis,1234"),
            "--admin-email",
            data.get('adminEmail', "mail@example.com"),
            "--project-name",
            data.get('projectName', "NethServer"),
            "--create-site",
            fqdn,
            "--force",
            "-n"
        ])

    agent.assert_exp(proc.returncode == 0)

    agent.set_env("INITIALIZED", True)
