#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os
import subprocess

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

pkg_name = data.get("packageName")
pkg_version = data.get("packageVersion")

# Ensure file exists
if not os.path.exists('packages.json'):
    with open('packages.json', 'w') as f:
        json.dump({"packages": [], "repositories": []}, f, indent=2)

with open('packages.json', 'r+') as f:
    packageData = json.load(f)
    packageData["packages"][pkg_name] = pkg_version
    f.seek(0)
    json.dump(packageData, f, indent=2)
    f.truncate()

composer_package = f"{pkg_name}:{pkg_version}"

proc = subprocess.run(['podman', 'exec', '--user=www-data', 'typo3-app', 'composer', 'require', composer_package])
agent.assert_exp(proc.returncode == 0)